import { CheckCircle, AlertCircle, FileText, ArrowLeft, ArrowRight } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import RecommendationCard from '../components/shared/RecommendationCard';

export default function ResultPage() {
  const { id } = useParams();

  // Mock Result Data
  const result = {
    date: 'August 16, 2026',
    score: 92,
    status: 'Healthy',
    findings: [
      { id: 1, text: 'Vitals are within normal ranges.', type: 'positive' },
      { id: 2, text: 'Slightly elevated stress markers detected.', type: 'neutral' },
    ],
    aiExplanation: "Your results indicate a healthy baseline. The slightly elevated stress markers are common and typically related to lack of sleep or mild dehydration. There are no critical anomalies detected in the provided data. Maintaining a balanced routine is advised.",
    recommendations: [
      { id: 1, title: 'Improve Hydration', category: 'Diet', explanation: 'Drink at least 2 liters of water daily to help reduce stress markers.' },
      { id: 2, title: 'Mindful Rest', category: 'Lifestyle', explanation: 'Incorporate 15 minutes of relaxation or meditation before bed.' },
    ]
  };

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8 space-y-8">
      <Link to="/history" className="inline-flex items-center text-sm font-medium text-slate-500 hover:text-slate-900">
        <ArrowLeft className="mr-2 h-4 w-4" />
        Back to History
      </Link>

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-slate-900">Health Check Result</h1>
          <p className="text-slate-500 mt-1">Check ID: {id || 'latest'} • {result.date}</p>
        </div>
        <div className="flex items-center gap-3 rounded-full bg-green-50 px-4 py-2 border border-green-100">
          <CheckCircle className="h-5 w-5 text-green-600" />
          <span className="font-semibold text-green-700">{result.status}</span>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="md:col-span-2 space-y-8">
          
          {/* Main Findings */}
          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h2 className="text-xl font-bold text-slate-900 mb-4 flex items-center gap-2">
              <FileText className="h-5 w-5 text-slate-500" />
              Key Findings
            </h2>
            <ul className="space-y-4">
              {result.findings.map(finding => (
                <li key={finding.id} className="flex items-start gap-3">
                  {finding.type === 'positive' ? (
                    <CheckCircle className="h-5 w-5 text-green-500 mt-0.5 shrink-0" />
                  ) : (
                    <AlertCircle className="h-5 w-5 text-amber-500 mt-0.5 shrink-0" />
                  )}
                  <span className="text-slate-700">{finding.text}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* AI Explanation */}
          <section className="rounded-2xl border border-slate-200 bg-blue-50/50 p-6 shadow-sm">
            <div className="mb-4">
              <div className="inline-flex items-center rounded-full border border-blue-200 bg-blue-100 px-3 py-1 text-xs font-semibold text-blue-800 mb-2">
                AI Explanation
              </div>
              <h2 className="text-xl font-bold text-slate-900">Understand your result</h2>
            </div>
            <p className="text-slate-700 leading-relaxed">
              {result.aiExplanation}
            </p>
            <div className="mt-4 text-xs text-slate-500 border-t border-blue-100 pt-4">
              This explanation is generated by AI to help you understand your results. It is not professional medical advice.
            </div>
          </section>

        </div>

        <div className="space-y-8">
          {/* Score Card */}
          <div className="rounded-2xl border border-slate-200 bg-slate-900 p-6 shadow-sm text-white text-center">
            <h3 className="text-slate-400 font-medium text-sm">Overall Score</h3>
            <div className="mt-4 text-6xl font-bold tracking-tight">
              {result.score}
            </div>
            <p className="mt-2 text-sm text-slate-300">Out of 100</p>
          </div>

          {/* Recommendations */}
          <div>
            <h2 className="text-lg font-bold text-slate-900 mb-4">Recommendations</h2>
            <div className="space-y-4">
              {result.recommendations.map(rec => (
                <RecommendationCard key={rec.id} recommendation={rec} />
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
